// Code generated by "stringer -type ManageMode"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Copy-0]
	_ = x[Hardlink-1]
}

const _ManageMode_name = "CopyHardlink"

var _ManageMode_index = [...]uint8{0, 4, 12}

func (i ManageMode) String() string {
	if i >= ManageMode(len(_ManageMode_index)-1) {
		return "ManageMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ManageMode_name[_ManageMode_index[i]:_ManageMode_index[i+1]]
}
